- name: Load a variable file based on the OS type
  include_vars: "{{ item }}"
  with_first_found:
  - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  - "vars/{{ ansible_os_family }}.yml"
  - "vars/defaults.yml"

- name:
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Run SSH tasks
  include_tasks:
    file: ssh.yml

- name: Set a message of the day
  copy:
    dest: /etc/motd
    src: files/motd
    owner: root
    group: root
    mode: 0644

- name: Set a login banner
  copy:
    dest: "{{ item }}"
    src: files/issue
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/issue
    - /etc/issue.net

- name: set timezone
  shell: timedatectl set-timezone America/Chicago
  ignore_errors: yes

- name: Run SSH tasks
  include_tasks:
    file: ansible.yml