- name: ensure ssh folder exists for user
  file: 
    path: "/home/{{ item.username }}/.ssh"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: "0600"
    state: directory
  with_items:  "{{ required_users }}"

- name: Deploy SSH Key (administrator)
  copy:
    dest: "/home/{{ item.username }}/.ssh/authorized_keys"
    src: "files/authorized_keys_{{ item.username }}"
    force: true 
    owner: "{{ item.username }}" 
    group: "{{ item.username }}" 
    mode: "0600"
  with_items:  "{{ required_users }}"    

- name: Remove Root SSH Configuration
  file: 
    path: /root/.ssh
    state: absent

- name: Copy Secured SSHD Configuration
  copy: 
    src: files/sshd_config_secured 
    dest: /etc/ssh/sshd_config 
    owner: root 
    group: root 
    mode: "0644"
  when: ansible_os_family == "Debian"   

- name: Copy Secured SSHD Configuration
  copy: 
    src: files/sshd_config_secured_redhat 
    dest: /etc/ssh/sshd_config 
    owner: root 
    group: root 
    mode: "0644"    
  when: ansible_os_family == "RedHat"   

- name: Restart SSHD
  systemd:
    name: sshd
    daemon_reload: yes
    state: restarted
    enabled: yes
  ignore_errors: yes
